Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -19,7 +19,7 @@ jobs:
 
   - script: |
       echo "Building Docker image..."
-      docker build -t oumaimakhelifi/dotnetproject:latest -f 03-app-dotnet/Dockerfile 03-app-dotnet || { echo "Build failed"; exit 1; }
+      docker build -t oumaimakhelifi/dotnetproject22:latest -f 03-app-dotnet/Dockerfile 03-app-dotnet || { echo "Build failed"; exit 1; }
     displayName: 'Build Docker Image'
 
   - script: |
@@ -30,5 +30,5 @@ jobs:
   - script: |
       echo "Deploying application..."
       docker pull oumaimakhelifi/dotnetproject:latest || { echo "Pull failed"; exit 1; }
-      docker run -d -p 3002:80 oumaimakhelifi/dotnetproject:latest || { echo "Run failed"; exit 1; }
+      docker run -d -p 3003:80 oumaimakhelifi/dotnetproject:latest || { echo "Run failed"; exit 1; }
     displayName: 'Deploy Application'
